[package]
name = "emit_example_getting_started"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2021"
publish = false

[dependencies.emit]
path = "../../"

[dependencies.emit_term]
path = "../../emitter/term"
