[package]
name = "emit_tracing"
version = "0.0.0"
edition = "2021"

[dependencies.emit]
path = "../../"

[dependencies.tracing]
version = "0.1"
default-features = false

[dependencies.tracing-core]
version = "0.1"
default-features = false
